name: Append new sighting to CSV

on:
  repository_dispatch:
    types: [new_sighting]

jobs:
  append:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Append sighting row
      run: |
        echo "${{ github.event.client_payload.csv_line }}" >> Database.csv

    - name: Commit changes
      run: |
        git config user.name "Nature-Soham Bot"
        git config user.email "actions@github.com"
        git add Database.csv
        git commit -m "Add new sighting"
        git push
