name: Proxy submission token

on:
  repository_dispatch:
    types: [proxy_request]

jobs:
  proxy:
    runs-on: ubuntu-latest
    steps:
      - name: Forward request to append workflow
        env:
          PAYLOAD: ${{ toJson(github.event.client_payload) }}
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.SUBMISSION_TOKEN }}" \
          https://api.github.com/repos/davidaitchison13/Nature-Soham/dispatches \
          -d "{\"event_type\":\"new_sighting\",\"client_payload\":${PAYLOAD}}"
